volumes:
  ct_vol:

networks:
  nt_net:
    name: nt_net

services:
  nt_db:
    container_name: ntVoteManager_db
    image: postgres:17-alpine
    restart: "no"
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=NTDataBase
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=voteManagerStrong@123