volumes:
  ct_vol:

networks:
  nt_net:
    name: nt_net

services:
  nt_db:
    container_name: nt_db
    image: postgres:17-alpine
    restart: "no"
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=NTDataBase
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=voteManagerStrong@123
  nt_queue:
    container_name: nt_queue
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
